version: '3'

services:
  backend:
    build:
      context: .
    volumes:
      - .:/image_uploads
    ports:
      - 3000:3000
    command: json-server -H 0.0.0.0 --watch /app/db.json
    hostname: renamed_backend